# PHMGen™ Documentation (Powerful Heightmap Generator ver.1.1)  
Version: 1.1  
Author: Max A. Vavaev  
Email: max14and@yandex.ru  
All rights reserved  

## Table of Contents  
[Overview](#overview)  
[Configuration](#configuration)  
[Detailed Algorithm Descriptions](#detailed-algorithm-descriptions)  
[Output Formats](#output-formats)  
[Supported Resolutions](#supported-resolutions)  
[Usage](#usage)  
[Performance Optimization](#performance-optimization)  
[Recommendations](#recommendations)  
[Update 1.1: Smart configuration and procedural rivers](Update-1.1:-Smart-configuration-and-procedural-rivers)  
[Reference Information](#reference-information)  

## Overview

PHMGen™ is a console application for procedural generation of realistic heightmaps. The program employs a comprehensive approach, simulating geological processes such as plate tectonics, erosion, sedimentation, and other phenomena to produce plausible terrain.

Heightmaps generated by the program are suitable for use in game engines (Unreal Engine, Unity), 3D editors, and landscape visualization systems.

The program supports generating both local terrain maps and entire planetary worlds—featuring a tectonic plate and continent simulation system.

### Key Features

- Multi-stage generation with the ability to enable/disable each stage  
- Plate tectonics simulation with convergent, divergent, and transform boundaries  
- Thermal and hydraulic erosion for realistic rivers and slopes  
- Batch generation of multiple maps in a single run  
- Export to 8-bit and 16-bit PNG  
- Multithreading for accelerated computation  
- Flexible configuration via a configuration file  
- Localization (Russian/English)  
- Reproducibility through a seed value  

### System Requirements

| Component | Requirement |
|-----------|-------------|
| OS        | Windows 10+ (earlier versions not tested) |
| RAM       | From ~7 MB in idle to 1.8 GB under default settings (8K resolution) |

### Quick Start

1. Run `PHMGen.exe`  
2. On first launch, choose the configuration file language (1 — Russian, 2 — English)  
3. Select map resolution (1–5, from 512 to 8192)  
4. Specify whether to use odd resolution (Y/N)  
5. Choose export format (1 — 8-bit, 2 — 16-bit PNG)  
6. Enter the number of maps to generate  
7. Wait for the process to complete  
8. The generated heightmap will be placed in the program folder  

### Generation Stages

The program executes generation in the following order:

| # | Stage                     | Description                         |
|---|---------------------------|-------------------------------------|
| 1 | Tectonics Simulation      | Plate creation and boundary modeling |
| 2 | Base Terrain              | Fractal noise (ridged FBM)          |
| 3 | Continents                | Separation of land and ocean        |
| 4 | Additional Features        | Volcanoes, craters, plateaus        |
| 5 | Domain Warping            | Organic shapes                      |
| 6 | Thermal Erosion           | Slope smoothing                     |
| 7 | Hydraulic Erosion         | Rivers, streams, and valleys        |
| 8 | Sedimentation             | Accumulation of deposits in lows    |
| 9 | Altitude Detail           | Height-based detail enhancement     |

Each stage can be enabled or disabled through the configuration file.

## Configuration

The configuration file is created automatically on first launch and contains parameters for all generation stages.

### Seed

The seed (`seed`) serves as the primary identifier for generation. Using the same seed with identical parameters produces reproducible results.

#### Special Notes on Seed Usage

- **Random seed generation**: set `seed = -1`  
- **Similarity in batch generation**: when generating multiple maps in one run, seeds will be similar, producing visually comparable maps.

### Stage Toggles

| Parameter                   | Default | Description                     |
|-----------------------------|---------|---------------------------------|
| `enable_tectonics`          | 1       | Plate tectonics simulation      |
| `enable_base_terrain`       | 1       | Fractal noise                   |
| `enable_continental_mask`   | 1       | Continent mask                  |
| `enable_voronoi_features`   | 1       | Volcanoes/craters/plateaus      |
| `enable_domain_warping`     | 1       | Domain warping                  |
| `enable_thermal_erosion`    | 1       | Thermal erosion                 |
| `enable_hydraulic_erosion`  | 1       | Hydraulic erosion               |
| `enable_sedimentation`      | 1       | Sedimentation                   |
| `enable_altitude_detail`    | 1       | Altitude detail                 |

Values: `1` — enabled, `0` — disabled

### Tectonics Parameters

*Note: "Range" column indicates recommended values, not hard limits.*

| Parameter                 | Default | Range     | Description                      |
|---------------------------|---------|-----------|----------------------------------|
| `tectonic_plates`         | 20      | 5–50      | Number of tectonic plates        |
| `boundary_influence_radius` | 30    | 10–100    | Boundary influence radius (px)   |
| `boundary_falloff`        | 2.0     | 1.0–4.0   | Influence falloff exponent       |
| `tectonic_blur_radius`    | 5       | 1–20      | Result smoothing radius          |

### Continent Parameters

| Parameter           | Default  | Range         | Description                             |
|---------------------|----------|---------------|-----------------------------------------|
| `sea_level`         | 0.4      | 0.0–1.0       | Sea level (higher = more water)         |
| `continent_scale`   | 0.0005   | 0.0001–0.01   | Scale (lower = larger continents)       |

### Voronoi Features Parameters (Volcanoes/Craters/Plateaus)

| Parameter           | Default | Range     | Description                        |
|---------------------|---------|-----------|------------------------------------|
| `voronoi_features`  | 30      | 0–100     | Number of features                 |
| `voronoi_strength`  | 0.3     | 0.1–1.0   | Height influence strength          |
| `voronoi_min_size`  | 20.0    | 5–50      | Minimum feature radius             |
| `voronoi_max_size`  | 100.0   | 50–300    | Maximum feature radius             |

### Domain Warping Parameters

| Parameter        | Default | Range     | Description                    |
|------------------|---------|-----------|--------------------------------|
| `warp_strength`  | 50.0    | 0–200     | Displacement strength (px)     |
| `warp_scale`     | 0.002   | 0.001–0.01| Warp noise scale               |

### Base Terrain Parameters

| Parameter       | Default  | Range         | Description                        |
|-----------------|----------|---------------|------------------------------------|
| `ridge_scale`   | 0.0012   | 0.0005–0.005  | Noise frequency (lower = larger)   |

### Thermal Erosion Parameters

| Parameter              | Default | Range     | Description                      |
|------------------------|---------|-----------|----------------------------------|
| `thermal_iterations`   | 12      | 1–50      | Number of smoothing passes        |
| `talus_angle`          | 0.005   | 0.001–0.02| Critical slope angle             |
| `thermal_erosion_rate` | 0.5     | 0.1–1.0   | Material displacement rate       |

### Hydraulic Erosion Parameters

| Parameter               | Default   | Range           | Description                              |
|-------------------------|-----------|-----------------|------------------------------------------|
| `erosion_iterations`    | 800000    | 100000–2000000  | Total number of water droplets           |
| `erosion_strength`      | 0.12      | 0.01–0.5        | Soil removal per droplet                 |
| `deposition_strength`   | 0.08      | 0.01–0.3        | Soil deposition per droplet              |
| `droplet_life`          | 120       | 50–300          | Max steps per droplet                    |
| `carry_capacity`        | 10.0      | 1.0–50.0        | Max sediment capacity per droplet        |
| `inertia`               | 0.15      | 0.0–0.5         | Droplet resistance to direction changes  |
| `evaporation`           | 0.015     | 0.001–0.05      | Water evaporation rate                   |
| `river_count_factor`    | 3.5       | 1.0–10.0        | River depth/width multiplier             |
| `accumulation_weight`   | 0.85      | 0.0–1.0         | Probability of droplet spawn in lows     |

### Sedimentation Parameters

| Parameter                 | Default | Range         | Description                  |
|---------------------------|---------|---------------|------------------------------|
| `sedimentation_iterations`| 5       | 1–20          | Number of passes             |
| `sedimentation_amount`    | 0.001   | 0.0001–0.01   | Material transport amount     |

### Altitude Detail Parameters

| Parameter                 | Default | Range         | Description                |
|---------------------------|---------|---------------|----------------------------|
| `altitude_detail_scale`   | 0.01    | 0.001–0.1     | Detail scale               |
| `altitude_detail_octaves` | 4       | 1–8           | Noise octaves              |

## Detailed Algorithm Descriptions

### 1. Plate Tectonics Simulation

Simulates lithospheric plate motion and terrain formation at plate boundaries.

**Workflow**:
1. Generate N plates with random centers  
2. Assign movement direction and velocity to each plate  
3. Build Voronoi diagram (determine point ownership)  
4. Classify boundary types:  
   • **Convergent** (collision) → mountains  
   • **Divergent** (separation) → rifts, depressions  
   • **Transform** (lateral slip) → minor ridges  
5. Propagate boundary influence inward across plates  
6. Apply Gaussian blur to remove artifacts  

**Boundary pressure formula**:  
`normalPressure = (v₁ · n) - (v₂ · n)`  

Where:  
- `v₁`, `v₂` — plate velocity vectors  
- `n` — boundary normal  

Positive pressure → convergent boundary (mountains)  
Negative pressure → divergent boundary (rifts)  
Near-zero → transform boundary  

---

### 2. Base Terrain (Ridged FBM)

Uses modified fractal Brownian motion with ridge enhancement, modulated by tectonic pressure:
- Collision zones → increased amplitude (tall mountains)  
- Rift zones → negative offset (depressions)

---

### 3. Continental Mask

Separates land and ocean using low-frequency noise.

---

### 4. Voronoi Features

Adds three types of geological formations:

| Type      | Probability | Influence Formula                                    | Description                     |
|-----------|-------------|------------------------------------------------------|---------------------------------|
| Volcano   | 50%         | `exp(-t² × 2) × strength`                            | Conical uplift                  |
| Crater    | 30%         | Center: `-exp(-t² × 3) × 0.5`<br>Edges: `+exp(-(t-0.8)² × 10) × 0.3` | Depression with raised rim       |
| Plateau   | 20%         | `smoothstep` with sharp edges                        | Flat elevated area              |

Where `t = distance / radius` — normalized distance from feature center.

---

### 5. Domain Warping

Creates more organic, natural shapes by displacing coordinates.

---

### 6. Thermal Erosion

Simulates material collapse on slopes exceeding the critical angle.

---

### 7. Hydraulic Erosion (Particle-based)

Simulates water droplet movement across terrain:

```
┌─────────────────────────────────────────────────────────────┐
│                    DROPLET LIFECYCLE                        │
├─────────────────────────────────────────────────────────────┤
│  1. Spawn (biased toward depressions for river formation)   │
│ 2. Compute gradient (bilinear interpolation) 				  │
│ 3. Update direction considering inertia 					  │
│ 4. Move droplet 											  │
│ 5. If slowing or ascending → deposit sediment				  │
│ 6. If accelerating → erode terrain  						  │
│ 7. Evaporate water 										  │
│ 8. Repeat until maxLife steps or out-of-bounds 	          │
└─────────────────────────────────────────────────────────────┘
```


---

### 8. Sedimentation

Models deposit accumulation in low-lying regions.

---

### 9. Altitude Detail

Adds fine-scale details primarily on elevated areas using subtle polishing noise.

## Output Formats

### 8-bit PNG (Grayscale)

- Value range: 0–255  
- File size: ~1 byte/pixel (+ compression)  
- Use case: previews, low-end games  
- Filename: `map_N_8bit.png`

### 16-bit PNG (Grayscale)

- Value range: 0–65535  
- File size: ~2 bytes/pixel (+ compression)  
- Byte order: Big-endian (PNG requirement)  
- Use case: professional workflows (Unreal Engine, Unity Terrain, 3ds Max, Blender, Cinema4D, World Machine etc.)  
- Filename: `map_N_16bit.png`

> **Recommendation**: Use 16-bit format for game engines—it provides smooth height transitions without visible "banding".

## Supported Resolutions

| Choice | Standard (n+1) | Even       | Note                                  |
|--------|----------------|------------|---------------------------------------|
| 1      | 513×513        | 512×512    | Fast generation                       |
| 2      | 1025×1025      | 1024×1024  | Optimal balance                       |
| 3      | 2049×2049      | 2048×2048  | High detail                           |
| 4      | 4097×4097      | 4096×4096  | Professional quality                   |
| 5      | 8193×8193      | 8192×8192  | Maximum detail                        |

> **Note**: The (n+1) format is standard for game engines (Unreal, Unity), enabling seamless tiling without edge artifacts.

## Usage

### Basic Generation (Recommended Settings)

1. Launch `PHMGen.exe`  
2. Resolution: 4 (4096×4096)  
3. Uneven resolution: N (standard 4097×4097)  
4. Format: 2 (16-bit)  
5. Number of maps: 5  

### Scenario: Erosion Only (No Tectonics)

For river- and valley-focused maps:

```ini
# config.txt
enable_tectonics=0
enable_base_terrain=1
enable_hydraulic_erosion=1
erosion_iterations=1500000
river_count_factor=5.0
accumulation_weight=0.9
```


## Scenario: Archipelago (High Water Coverage)

```ini
# config.txt
sea_level=0.6
continent_scale=0.001
voronoi_features=50
voronoi_max_size=150.0
```

## Scenario: Mountain Range

```ini
# config.txt
tectonic_plates=8
boundary_influence_radius=50
boundary_falloff=1.5
enable_voronoi_features=0
thermal_iterations=5
```

## Scenario: Flat Plain with Rivers

```ini
# config.txt
enable_tectonics=0
enable_voronoi_features=0
sea_level=0.3
erosion_iterations=1200000
river_count_factor=8.0
thermal_iterations=20
```

## Scenario: Volcanic Island

```ini
# config.txt
tectonic_plates=5
sea_level=0.55
voronoi_features=15
voronoi_strength=0.5
voronoi_min_size=30.0
voronoi_max_size=80.0
```

---

# Recommendations

## Multithreading

The program automatically utilizes all available CPU cores:

```cpp
unsigned int numThreads = std::thread::hardware_concurrency();
```

Each stage is split into horizontal strips processed in parallel.

## Performance

The program is built on modern architecture with optimized methods and state-of-the-art mathematical algorithms. It uses minimal memory and parallelizes computations wherever possible.

## Optimization Tips for Low-End PCs

1. **Reduce `erosion_iterations`** — the most resource-intensive stage.
2. **Disable unnecessary stages** (e.g., `enable_sedimentation=0`
3. **Lower `boundary_influence_radius`** — to speed up tectonics
4. **Use lower resolution** for testing

# Update 1.1: Smart configuration and procedural rivers

In version 1.1, the main focus is on usability (UX) and expanding the biological/hydrological reliability of the relief.

## 0. Post-processing of the output card with parameter input
 - Adjustment of the final brightness (soft)
 - Correction of the final Gaussian blur

## 1. Dynamic configuration management
The system of working with `config.txt `has been completely redesigned:
- **Automatic recovery**: If there are no new parameters in the file, the program will add them without resetting your old settings.
- **Hot Reload**: The program monitors changes in the configuration file. If you have changed `config.txt ` during operation, PHMGen™ will suggest:
1. Apply the new settings immediately.
2. Continue with the old ones.
  3. Cancel generation [cite: 58, 63].
- **Change Control**: Before restarting, the program displays a list of specific parameters that have been changed and their old/new values.

## 2. New Stage: River Generation (Spline Rivers)
In addition to hydraulic erosion, the stage of creating large river systems based on splines has been added.
- **`enable_rivers`**: Enabling/disabling a stage.
- **`river_count`**: The number of main river basins.
- **`river_meander`**: Tortuosity coefficient (from 0 to 1).
- **`river_delta_chance` & `river_delta_branches'**: Allows you to create complex river deltas when flowing into the ocean.
- **`river_oxbow_chance`**: The chance of old men (backwaters) appearing in the riverbeds.

##3. Advanced tectonics and mask options
Added fine-tuning to more precisely control the shape of the continents:
- **`tectonic_boundary_strength`**: Controls the height of mountain ranges at the junctions of the plates.
- **`continent_transition`**: Adjusts the width of the coastline (smooth transition).
- **`continent_se_depth`**: Global multiplier of the depth of the ocean floor.
- **`continent_land_boost`**: Additional elevation of the entire land relative to sea level.

---

# Background information

## License

**The author:** Max A. Vavaev  
**All rights reserved**

---

## Contacts and support

If you find errors or for suggestions for improvement, please contact the author of the program.
Email address: max14and@yandex.ru
